import { jsPDF } from 'jspdf'

export function downloadSpecSheet(product, company, lang) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const name = product[`name_${lang}`] || product.name_en
  const desc = product[`desc_${lang}`] || product.desc_en
  const specs = product.specs || []
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()

  doc.setFillColor(15, 118, 110)
  doc.rect(0, 0, W, 92, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(19)
  doc.text('PRODUCT SPECIFICATION SHEET', 40, 44)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(12)
  doc.text(company.name, 40, 68)

  doc.setTextColor(20, 20, 20)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(name, 40, 132)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  const descLines = doc.splitTextToSize(desc, W - 80)
  doc.text(descLines, 40, 154)

  let y = 154 + descLines.length * 14 + 24
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Specifications', 40, y)
  y += 22
  doc.setFontSize(11)
  specs.forEach((s) => {
    doc.setFont('helvetica', 'bold')
    doc.text(s.label_en, 40, y)
    doc.setFont('helvetica', 'normal')
    doc.text(String(s.value), 270, y)
    y += 20
  })

  doc.setFontSize(9)
  doc.setTextColor(130, 130, 130)
  doc.text(
    `Generated by ${company.name} - ${new Date().toLocaleDateString()}`,
    40,
    H - 30
  )

  doc.save(`SpecSheet_${product.id}_${lang}.pdf`)
}
